config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root to: 'pages#home'
  root to: "products#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products do
    resources :proportions, only: [:new, :create]
  end
  resources :proportions, only: [:destroy]
  get 'statistics', to: 'pages#statistics'
end

app/views/shared/_flashes.htlm.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#">FAQ</i></a>
    <a href="#">CONTACT</i></a>
    <a href="#">TERMS</i></a>
  </div>
  <div class="footer-copyright">
    <h3>The Good Wardrobe</h3>
  </div>
</div>

app/views/shared/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-sm-offset-12">

<%= simple_form_for @product do |f| %>
  <%= f.input :title, label: "Titre", placeholder: 'red dress', error: 'Title is mandatory, please specify one' %>
  <%= f.input :description, label: "Description", placeholder: 'this is a red dress is totally brand new', error: 'Please enter a short description' %>
  <%= f.input :second_hand %>
  <%= f.input :purchase_date, label: "Purchase date", placeholder: 'AAAA/MM/DD' %>
  <%= f.input :brand, label: "Brand", placeholder: 'Dior, H&M...'%>
  <%= f.input :origin, label: "Made in", :collection => ["China", "Bangladesh", "Italy", "Turkey", "India", "Tunisia", "Vietnam", "Portugal", "Autre"], placeholderder: 'China, India...'%>
  <%= f.input :category, label: "Category", :collection => ["Dress", "Jeans", "Shirt", "Pants", "Skirt", "T-shirt", "Sweatshirt", "Coat", "Jacket"] %>
  <%= f.input :photo, as: :file %>
  <% if @product.category.blank? %>
    <%= f.submit "Submit", class: "btn btn-primary" %>
  <% else %>
    <%= f.submit "Update", class: "btn btn-primary" %>
  <% end %>
<% end %>
  <br>
  <br>
   </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "The Good Wardrobe", root_path, class: "navbar-brand" %>
    <%#image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "MY WARDROBE", root_path, class: "nav-link" %>
        </li>
         <li class="nav-item active">
          <%= link_to "MY STATS", statistics_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <!--<%= link_to "MY PROFILE", edit_user_registration_path, class: "nav-link", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>-->
          <%= link_to "MY PROFILE", edit_user_registration_path, class: "nav-link" %>
          <!--<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Edit my profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>-->
        </li>
        <li class="nav-item active"><%= link_to "LOG OUT", destroy_user_session_path, method: :delete, class: "nav-link" %></li>
      <% else %>
        <li class="nav-item">
          <%= link_to "LOG IN", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar2.html.erb
<body class="hero-anime">

  <div class="navigation-wrap bg-light start-header start-style">
<!--     <div class="container">
 -->      <div class="row">
        <div class="col-12">
          <nav class="navbar navbar-expand-md navbar-light">

            <a class="navbar-brand" href="https://themeforest.net/user/ig_design/portfolio" target="_blank"><img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/1462889/logo.svg" alt=""></a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav ml-auto py-4 py-md-0">
                <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4 active">
                  <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Home</a>
                  <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                    <a class="dropdown-item" href="#">Another action</a>
                  </div>
                </li>
                <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
                  <a class="nav-link" href="#">Portfolio</a>
                </li>
                <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
                  <a class="nav-link" href="#">Agency</a>
                </li>
                <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
                  <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Services</a>
                  <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                    <a class="dropdown-item" href="#">Another action</a>
                  </div>
                </li>
                <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
                  <a class="nav-link" href="#">Journal</a>
                </li>
                <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
                  <a class="nav-link" href="#">Contact</a>
                </li>
              </ul>
            </div>

          </nav>
        </div>
      </div>
    <!-- </div> -->
  </div>
<!--   <div class="section full-height">
    <div class="absolute-center">
      <div class="section">
        <div class="container">
          <div class="row">
            <div class="col-12">
        <h1><span>B</span><span>o</span><span>o</span><span>t</span><span>s</span><span>t</span><span>r</span><span>a</span><span>p</span> <span>4</span><br>
        <span>m</span><span>e</span><span>n</span><span>u</span></h1>
        <p>scroll for nav animation</p>
            </div>
          </div>
        </div>
      </div>
      <div class="section mt-5">
        <div class="container">
          <div class="row">
            <div class="col-12">
              <div id="switch">
                <div id="circle"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="my-5 py-5"> -->
  </div>

<!-- Link to page
================================================== -->

<a href="https://themeforest.net/user/ig_design/portfolio"      class="link-to-portfolio" target=”_blank”></a>

</body>