config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root to: 'pages#home'
  root to: "products#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products do
    resources :proportions, only: [:new, :create]
  end
  resources :proportions, only: [:destroy]
  get 'statistics', to: 'pages#statistics'
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :proportions, dependent: :destroy
  has_many :materials, through: :proportions
  validates :description, presence: true, length: { minimum: 25 }
  # validates :second_hand, presence: true
  validates :title, presence: true
  validates :status, presence: true
  validates :category, presence: true

  enum status: {
    "in my wardrobe" => 1,
    "to sell" => 2,
    "to donate" => 3,
    "to recycle" => 4,
    "to throw away" => 5,
    "sold" => 6,
    "donated" => 7,
    "recycled" => 8,
    "thrown away" => 9
  }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = current_user.products.all
  end

  def show
    @proportion = Proportion.new
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    if @product.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @product.update(product_params)
      respond_to do |format|
        format.html { redirect_to products_path }
        format.js
      end
      else
        respond_to do |format|
          format.html { render :edit }
          format.js
        end
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end
  def product_params
    params.require(:product).permit(:title, :description, :category, :second_hand, :status, :photo, :origin, :brand)
  end


end

app/views/products/_status.html.erb
<div class="dropdown" id="status" data-product-id=<%= product.id %>>
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <%= product.status %>
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <% Product.statuses.each_key do |name| %>
      <%= simple_form_for(product, remote: true) do |f| %>
       <%= f.input :status, as: :hidden, input_html: {value: name} %>
       <%= f.button :submit, name, id: "change_status" %>
      <% end  %>
    <% end %>
  </div>
</div>

app/views/products/edit.html.erb
<div class="container">
  <div class="row">
  <div class="col-2"></div>
  <div>
  <h1 class="col-xs-8 text-center"><%=  @product.title %></h1>
   </div>
   </div>
</div>
  <%= render 'shared/form' %>
</div>

app/views/products/index.html.erb
<div class="container-wardrobe">
<h1 class="title-index">My Wardrobe</h1>
<!-- <p class="add-product"><%= link_to "New Product", new_product_path(@product), class: "btn btn-primary new-prod" %></p> -->
<p class="add-product">
<%= link_to new_product_path(@product), class: "btn btn-primary new-prod" do %>
  <i class="material-icons">add</i>
<% end %>
</p>

<div class="card-all">
  <% @products.each do |product| %>
    <div class="card-trip">
      <%if product.photo.attached? %>
        <div class="img-card">
          <!-- <span class="tag">status</span> -->
          <%= render "products/status", product: product  %>
          <%= link_to product_path(product) do %>
            <%=cl_image_tag product.photo.key%>
          <% end %>
        </div>
        <%else%>
        <div class="img-card">
          <!-- <span class="tag">status</span> -->
          <%= render "products/status", product: product  %>
          <%= link_to product_path(product) do %>
            <%= cl_image_tag("default-image_m00t8o.jpg") %>
          <% end %>
        </div>
      <%end%>
      <div class="card-trip-infos">
        <div>
          <%= link_to product_path(product) do %>
            <h3 class="title-product"><%=product.title%></h3>
          <% end %>
          <%if product.description.length >= 140 %>
            <p><%=product.description.first(140)%>...</p>
          <%else%>
            <p><%=product.description%></p>
          <%end%>
        </div>
        <!-- <p class="card-trip-pricing"><%= link_to "See more", product_path(product) %></p> -->
      </div>
    </div>
  <% end %>
</div>
</div>

app/views/products/new.html.erb
<div class="container">
  <div class="row">
  <div class="col-2"></div>
  <div>
  <h1 class="col-xs-8 text-center">Add a new Product</h1>
   </div>
   </div>
</div>
  <%= render 'shared/form' %>
</div>

app/views/products/show.html.erb
<div class="container-show">
  <!--   <h1>Produit : <%= @product.title %></h1> -->
<div class="big-container-show">
 <div class="container-left">
  <div class="img-show">
    <%if @product.photo.attached? %>
    <!-- <span class="tag">status</span> -->
    <!--<span class="tag"><%= link_to "Edit ", edit_product_path(@product) %></span>-->
     <div class="fixed-action-btn horizontal click-to-toggle spin-close">
        <a class="btn-floating btn-large bg-blue-sea">
          <i class="material-icons">edit</i>
        </a>
        <ul>
          <li>
            <%= link_to product_path(@product),
                  method: :delete,
                  data: { confirm: "Are you sure?" }, class: "btn-floating delete-show" do%>
                  <i class="material-icons">delete</i>
            <% end %>
          </li>
          <li>
            <%= link_to edit_product_path(@product), class: "btn-floating tag darken-1" do %>
              <i class="material-icons">mode_edit</i>
            <% end %>
          </li>
          <li>
            <%= link_to root_path, class: "btn-floating back" do %>
              <i class="material-icons">home</i>,
            <% end %>
          </li>
        </ul>
      </div>

    <%= cl_image_tag @product.photo.key, class: "materialboxed" %>
    <%else%>
    <div class="fixed-action-btn horizontal click-to-toggle spin-close">
        <a class="btn-floating btn-large bg-blue-sea">
          <i class="material-icons">edit</i>
        </a>
        <ul>
          <li>
            <%= link_to product_path(@product),
                  method: :delete,
                  data: { confirm: "Are you sure?" }, class: "btn-floating delete-show" do%>
                  <i class="material-icons">delete</i>
            <% end %>
          </li>
          <li>
            <%= link_to edit_product_path(@product), class: "btn-floating tag darken-1" do %>
              <i class="material-icons">mode_edit</i>
            <% end %>
          </li>
          <li>
            <%= link_to root_path, class: "btn-floating back" do %>
              <i class="material-icons">home</i>,
            <% end %>
          </li>
        </ul>
      </div>

    <%= cl_image_tag("default-image_m00t8o.jpg", class: "materialboxed") %>
    <%end%>
  </div>
</div>
  <div class="text-show">
    <!-- title -->
    <span class="main-title-product"><%= @product.title %></span>

    <!-- description-->
    <p><%= @product.description%></p>

    <!--second hand-->
    <div>
      <% if @product.second_hand == true %>
          <span class="title-details">I bought it</span>
          <span>Second hand</span>
        <% else %>
          <span class="title-details">I bought it</span>
          <span>New</span>
      <%end %>
    </div>

    <!--category-->
    <div class="details-pdt">
      <% unless @product.category == nil %>
        <span class="title-details">Category</span>
        <span> <%= @product.category%></span>
      <% else %>
        <span class="missing"> *You should add one category in page edit </span>
      <% end  %>
    </div>

    <!--brand-->
    <div class="details-pdt">
      <% unless @product.brand == nil %>
        <span class="title-details">Brand</span>
        <span><%= @product.brand%></span>
      <% else %>
        <span class="missing"> *You should add the brand in page edit </span>
      <%end %>
    </div>

    <!--made in-->
    <div class="details-pdt">
      <% unless @product.origin == "" %>
        <span class="title-details">Made in</span>
        <span><%= @product.origin %></span>
      <% else %>
        <span class="missing"> *You should add the origin in page edit </>
      <% end %>
    </div>


    <!--composition-->
    <div>
      <ul id="proportions">
        <% @product.proportions.each do |proportion| %>
        <%= render "proportions/show", proportion: proportion  %>
        <% end %>
      </ul>
    </div>

    <div class="add-proportion">
      <span class="title-details">Composition</span>
      <%= render "proportions/form", proportion: @proportion, product: @product  %>
    </div>

      <!-- Click-only FAB html from http://materializecss.com/buttons.html  -->

<!-- <div class="fixed-action-btn">
  <a class="btn-floating btn-large red">
    <i class="large material-icons">mode_edit</i>
  </a>
  <ul>
    <li><a class="btn-floating red"><i class="material-icons">insert_chart</i></a></li>
    <li><a class="btn-floating yellow darken-1"><i class="material-icons">format_quote</i></a></li>
    <li><a class="btn-floating green"><i class="material-icons">publish</i></a></li>
    <li><a class="btn-floating blue"><i class="material-icons">attach_file</i></a></li>
  </ul>
</div>
-->


      </div>
    </div>
    <div>
  </div>


</div>
</div>

app/views/products/update.js.erb
function refreshStatus(innerHTML) {
  const changeStatus = document.querySelector("[data-product-id='<%= @product.id %>']");
  changeStatus.innerHTML = innerHTML;
}

refreshStatus('<%= j render "products/status", product: @product %>');